apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  name: prometheus
  namespace: monitoring-backend
secrets:
- name: prometheus-token-dff2j  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes/metrics
  - pods
  - services
  - nodes
  - nodes/proxy
  verbs:
  - get
  - watch
  - list
- nonResourceURLs:
  - /metrics
  verbs:
  - get          
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: monitoring-backend  
