apiVersion: v1
data:
  all.yml: |
    - name: 'default'       # name of this dashboard configuration (not dashboard itself)
      org_id: 1             # id of the org to hold the dashboard
      folder: ''            # name of the folder to put the dashboard (http://docs.grafana.org/v5.0/reference/dashboard_folders/)
      type: 'file'          # type of dashboard description (json files)
      options:
        folder: '/var/lib/grafana/dashboards'       # where dashboards are
kind: ConfigMap
metadata:
  name: dashboard-source
  namespace: monitoring-backend
---
apiVersion: v1
data:
  all.yml: |
    datasources:
    - name: ${DS_PROMETHEUS}
      type: 'prometheus'
      access: 'proxy'
      org_id: 1
      url: 'http://prometheus-web.monitoring-backend.svc.cluster.local'
      is_default: true
      version: 1
      editable: true
kind: ConfigMap
metadata:
  name: datasource
  namespace: monitoring-backend
