apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1ETXdOakUwTXpBMU9Gb1hEVEk1TURNd016RTBNekExT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2JaCmVRREVsYTJacWxiVXNkUmplcFNEaDZDK2x4aEtLYUVqVGRrbzZjYktCVFpQQVYydnhrM3NFdE9JYm0zYThjVUUKd0FPZXpoUkN1L2dDdkJNaU8za3kvOGVxanZxK1VLZmJpOFlNczRxZnQ4UFcvUE0zdzVHRHNUTld3cCtJS0N3ZwpSc1ZrSUxBeGtBSVZ6Qkt0YjlicTcxR3FYbjdRdy9LdFlKL2U4bi94OGYvVDhXZSs4MUFBRFNGWEtuY2FXU2R0CjFxMzVyVzhLcG52dnUyNG5ZZnFnOEJwN0JSdmw2eTh6Y20rTzdWRnF2QVZMWkNwRHdRRExjNkZNZmpXczFBMFQKeUdoRDZEYnRUWk5WQmkxZzlzNjRPK2hqR0xYRGtQQ3FENCtHYWFkVGlhNmJ1aTZ6RWVrYXhNNDNMSTFodXBoRwpkVlhjN1U5Sk0zNDJCcGpwakZjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFYmM4b2NKT3ZURVEyYTZXWW1lQ2srVVkxNEwKODBjRHhLdjZ4SWtsU3JHKzNqUVFZQU00dmNRNXZJY1hOYjkwRkVSRFN3ZHRqd3lvNVF0M3MwSXYyWW41VHpSYgowNWpzdHRCWXdHd1drSlppK3FNaytRQk1GWFZUWHZBSXVZTERxUUxqbERydzFTN3NnNC9XaWl1WUUvVkhvNlZZCmxKejhURUR6NU4xMzgzaXcyT1BkRWVYV1RHdVlpZ2lvaUZ1MndtZ3ZVWWRoMDlqa1AzSndlakVMdEVlODVhOTEKQU0wb3JxSlZPakVtTWdQMkd4dmdERldpRGtJQUJ2cUhyQVZEYkdrNGNRMEpBY29qMVFHSW8wUGNVY2FpVHdBYwpqN3F0WVJPdU4vWUNvTTRQTFR5dG4vL3ZROVZxT3VJTTVWV0Iwbm5qYXlXaS91NlJKbnd5dE1kaW14VT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  namespace: ZWxrLWxvZ3M=
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklpSjkuZXlKcGMzTWlPaUpyZFdKbGNtNWxkR1Z6TDNObGNuWnBZMlZoWTJOdmRXNTBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5dVlXMWxjM0JoWTJVaU9pSmxiR3N0Ykc5bmN5SXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWamNtVjBMbTVoYldVaU9pSmxiR0Z6ZEdsamMyVmhjbU5vTFhSdmEyVnVMV05pZEhGMElpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVibUZ0WlNJNkltVnNZWE4wYVdOelpXRnlZMmdpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1MWFXUWlPaUl5TVdZek5EbGxOeTAwTVRjMUxURXhaVGt0WW1RM01TMDVOakF3TURBeFlUY3pNRGdpTENKemRXSWlPaUp6ZVhOMFpXMDZjMlZ5ZG1salpXRmpZMjkxYm5RNlpXeHJMV3h2WjNNNlpXeGhjM1JwWTNObFlYSmphQ0o5Lk55aUJJN09Ja3FvVTdFaS1xeXpTTXpkcXNSVjhieTNaYUg2R2tYR2NaZWhUeXdzUXJKeVBRWG5pd1lNQ0VUNE84UmI5MzlDVzUteWI3NXV1em9hbVJlTl9tOFVnTGVNVGUxSjZOeFBCOE51WVlzLXJ4R0FVMldrMmtwLUhFa0IzdHpBLV9qeU1iVWJBMEszREpzSi1pNnI0bE9wQVNXajRMSE93TTZMcnlBbFBnZnpBd3JzLUlJaExkTUdFcUpWMGdDa0hmYU5sTDl2UVZOZTV0bXNkZUphb0F4N1haR2pjNnBPUFNkRG50dGl4MGlkUEQ1NXZ3SWdES1cyeW9YbFJ1NUZFa3Vkallha0hTZGFDVDZ4VlA4bVRoRnhLUUdTUHJhYVB2T1BRWVdCSHFBQ0dyaENMNmlXZVRzTDRiUF9YZ0o5bjMxdURBWEU2cTRGWGxXMnMxUQ==
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: elasticsearch      
  name: elasticsearch-token-cbtqt
  namespace: efk-logs
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  labels:
    component: elasticsearch
    role: client
  name: elasticsearch
  namespace: efk-logs
secrets:
- name: elasticsearch-token-cbtqt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  labels:
    component: elasticsearch
    role: client
  name: elasticsearch
rules:
- apiGroups:
  - ""
  resources:
  - services
  - namespaces
  - endpoints
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  labels:
    component: elasticsearch
    role: client
  name: elasticsearch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch-logging
subjects:
- kind: ServiceAccount
  name: elasticsearch
  namespace: efk-logs
