apiVersion: v1
kind: Service
metadata:
  namespace: efk-logs
  name: elasticsearch-data
  labels:
    app: elasticsearch
    role: data
spec:
  ports:
  - port: 9300
    name: transport
  selector:
    app: elasticsearch-data
    role: data
